//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCafe_Winform.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.ThongTinHoaDon = new HashSet<ThongTinHoaDon>();
        }
    
        public int Id { get; set; }
        public System.DateTime NgayVao { get; set; }
        public Nullable<System.DateTime> NgayRa { get; set; }
        public int IdBan { get; set; }
        public int TrangThai { get; set; }
    
        public virtual BanThucAn BanThucAn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinHoaDon> ThongTinHoaDon { get; set; }
    }
}
