//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCafe_Winform.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyQuanCafeEntities : DbContext
    {
        public QuanLyQuanCafeEntities()
            : base("name=QuanLyQuanCafeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BanThucAn> BanThucAn { get; set; }
        public virtual DbSet<DanhMucThucAn> DanhMucThucAn { get; set; }
        public virtual DbSet<HoaDon> HoaDon { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoan { get; set; }
        public virtual DbSet<ThongTinHoaDon> ThongTinHoaDon { get; set; }
        public virtual DbSet<ThucAn> ThucAn { get; set; }
    
        public virtual ObjectResult<UPS_TaoListBan_Result> UPS_TaoListBan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UPS_TaoListBan_Result>("UPS_TaoListBan");
        }
    }
}
