//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCafe_Winform.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public string TenDangNhap { get; set; }
        public string TenHienThi { get; set; }
        public string MatKhau { get; set; }
        public int Loai { get; set; }
    }
}
