//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCafe_Winform.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinHoaDon
    {
        public int Id { get; set; }
        public int IdHoaDon { get; set; }
        public int IdThucAn { get; set; }
        public int SoLuong { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual ThucAn ThucAn { get; set; }
    }
}
