//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCafe_Winform.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThucAn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThucAn()
        {
            this.ThongTinHoaDon = new HashSet<ThongTinHoaDon>();
        }
    
        public int Id { get; set; }
        public string TenThucAn { get; set; }
        public int IdDanhMuc { get; set; }
        public double Gia { get; set; }
    
        public virtual DanhMucThucAn DanhMucThucAn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinHoaDon> ThongTinHoaDon { get; set; }
    }
}
